name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: gitleaks-action with defaults
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: gitleaks-action with config
        uses: actions/checkout@v2
        with:
          repository: GiriRaj249/gitleaks-actions
          ref: main
          path: ./action
      - name: run git actions
        uses: ./action
        
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
           status: ${{ job.status }}
              notification_title: '{workflow} has {status_message}'
              message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
              footer: 'Linked Repo <{repo_url}|{repo}>'
              notify_when: 'failure'
              mention_users: 'U0160UUNH8S,U0080UUAA9N'
              mention_users_when: 'failure,warnings'
              mention_groups: 'SAZ94GDB8'
              mention_groups_when: 'failure,warnings'
              notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      
