name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitleaks-action with defaults
      	with:
	  fetch-depth: '0'  
        uses: GiriRaj249/gitleaks-actions@main
      - name: gitleaks-action with config
        uses: GiriRaj249/gitleaks-actions@main
        with:
          config-path: .gitleaks.yml
          token: ${{ secrets.Git_Token }}
 
