name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: gitleaks-action with defaults
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: gitleaks-action with config
        uses: actions/checkout@v2
        with:
          repository: GiriRaj249/gitleaks-actions
          ref: main
          token: ${{ secrets.Git_Token }}
          path: ./action
      - name: run git actions
        uses: ./action
        
      - name: Report Status
        if: always()
        uses: GiriRaj249/notify-slack-action@main
        with:
          status: ${{ job.status }}
          token: ${{ secrets.Git_Token }}
          notify_when: 'failure'
        env:
           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      
