name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: gitleaks-action with defaults
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: gitleaks-action with config
        uses: actions/checkout@v2
        with:
          repository: GiriRaj249/gitleaks-actions
          ref: main
          token: ${{ secrets.Git_Token }}
          path: ./action
      - name: run git actions
        uses: ./action
        
      - name: Send Slack notification
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      
