name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        token: ${{ secrets.Git_Token }}
      - name: gitleaks-action with defaults
        uses: GiriRaj249/gitleaks-actions@main
      - name: gitleaks-action with config
        uses: GiriRaj249/gitleaks-actions@main
        with:
          config-path: .gitleaks.toml
